### ISSUE TITLE
Empty replies from server

### ISSUE THREAD

**Issue by vladimirpetukhov** [BitcoinAmiens/docker-dogecoin#4]
## Start
I just copied your Dockerfile and ran the commands below.

The RPC server returns curl: (52) Empty reply from the server for every curl request.
I used the current Docker file and tried some different variants.
With Dockerfile iI see this error when container was started:  Binding RPC on address ::1 port 22555 failed.
When I try this variant:
```
FROM ubuntu:latest

RUN apt-get update

RUN apt-get -y install wget

WORKDIR /usr/src

RUN wget https://github.com/dogecoin/dogecoin/releases/download/v1.14.5/dogecoin-1.14.5-x86_64-linux-gnu.tar.gz
RUN tar -xzvf dogecoin-1.14.5-x86_64-linux-gnu.tar.gz
RUN chmod +x dogecoin-1.14.5/bin/dogecoind dogecoin-1.14.5/bin/dogecoin-cli
RUN ln -s /usr/src/dogecoin-1.14.5/bin/dogecoind /usr/bin/dogecoind
RUN ln -s /usr/src/dogecoin-1.14.5/bin/dogecoin-cli /usr/bin/dogecoin-cli

EXPOSE 22555 22556 44555 44556 18444 18332

CMD ["dogecoind", "-printtoconsole", "-rpcport=22555","-rpcuser=user","-rpcpassword=pass","-rpcbind=","-rpcallowip=127.0.0.1"]
```
don't have any errors but again, the container was fired successfully but still, I can't access RPC.

### OS
Windows 10
Docker Desktop

### Commands to build
```
docker build -t dogecoind-img . --progress=plain
docker run -p 22556:22556 -p 22555:22555 -d -v $PWD/data:/root/.dogecoin dogecoind-img
docker run -d -v $PWD/data:/root/.dogecoin dogecoind-img
```

**Comment by rllola** [comment]
You can try to run the container with `--network=host` and use the dogecoin config `"-rpcallowip=0.0.0.0/0"`.

I have also had issue with port forwarding. Using the host network option worked for me. I am not sure if it is good practice tho.
